import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Stock Screener</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen">
        <div className="py-12 sm:py-8 md:py-12 lg:py-14 xl:py-12 2xl:py-12">
          <div className="mx-auto max-w-[800px] lg:px-8 xl:max-w-7xl">
            <div className="flex h-1/2 flex-col items-center justify-end pb-4">
              <h1 className="text-center text-4xl font-bold tracking-tight text-black sm:text-6xl sm:tracking-tight lg:text-[4rem] xl:text-[6rem] xl:tracking-tight 2xl:text-[6.5rem]">
                The most average stock screener you&apos;ll ever use
              </h1>
              <p className="pt-4 text-center text-2xl font-bold tracking-tight text-black sm:text-[2rem] sm:tracking-tight md:text-[2rem] lg:text-[2rem] xl:pt-8 xl:text-[2rem] xl:tracking-tight 2xl:text-[2rem]">
                (but hey, it&apos;s free)
              </p>
            </div>

            <div className="mt-4 flex w-full items-center justify-center gap-4 xl:mt-8">
              <Link
                href="screener"
                className="mb-2 me-2 flex items-center rounded-full border border-gray-200 bg-black px-5 py-2.5 text-lg font-medium text-white hover:bg-slate-700 hover:text-white focus:z-10 focus:outline-none focus:ring-4 focus:ring-gray-100 "
              >
                Get Started
                <svg
                  viewBox="0 0 28 24"
                  xmlns="http://www.w3.org/2000/svg"
                  className="-mr-2 ml-1 h-8 w-8"
                >
                  <path
                    d="M10 7L15 12L10 17"
                    stroke="#fff"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  />
                </svg>
              </Link>
              <button
                type="button"
                className="mb-2 me-2 flex items-center rounded-full border border-gray-200 bg-white px-5 py-2.5 text-lg font-medium text-gray-900 hover:bg-gray-100 hover:text-black focus:z-10 focus:outline-none focus:ring-4 focus:ring-gray-100 "
              >
                GitHub
                <svg
                  viewBox="0 0 84 48"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="#000000"
                  className="-mr-2 ml-2 h-8 w-8"
                >
                  <path d="M0 0h48v48H0z" fill="none" />
                  <g id="Shopicon">
                    <polygon points="44,30 40,30 40,38 8,38 8,10 20,10 20,6 4,6 4,42 44,42 "></polygon>
                    <polygon points="26,26.828 40,12.828 40,24 44,24 44,6 26,6 26,10 37.172,10 23.172,24 "></polygon>
                  </g>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
